modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "HaXr"
description = "${description}"
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "common.mixins.json"